name: hnet
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blas=2.113
  - blas-devel=3.9.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=36.0.1
  - cudatoolkit=10.2.89
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - fsspec=2022.1.0
  - future=0.18.2
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.43.0
  - idna=3.3
  - importlib-metadata=4.11.1
  - intel-openmp=2022.0.0
  - jbig=2.1
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libffi=3.4.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.6
  - mkl=2022.0.0
  - mkl-devel=2022.0.0
  - mkl-include=2022.0.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - numpy=1.22.2
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pillow=9.0.1
  - pip=22.0.3
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.9.10
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-lightning=1.5.10
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.12
  - pyu2f=0.1.5
  - pyyaml=6.0
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scipy=1.8.0
  - setuptools=59.5.0
  - six=1.16.0
  - sqlite=3.37.0
  - tbb=2021.5.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchmetrics=0.7.2
  - torchvision=0.11.3
  - tqdm=4.62.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2021e
  - ucrt=10.0.20348.0
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - werkzeug=2.0.3
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
